name: "Yaml configuration"
description: "read IS CI/CD yaml configuration"
inputs:
  env:
    description: "environment running cicd workflow"
    required: true
  role:
    description: "auth role for cicd workflow"
    required: false
    default: build
  config:
    description: "configuration for cicd workflow"
    required: true

outputs:
  aws_account:
    description: "aws account in given env"
    value: ${{ steps.get-settings.outputs.aws_account }}
  aws_role: 
    description: "aws role in given env" 
    value: ${{ steps.get-settings.outputs.aws_role }}
  aws_region: 
    description: "aws region in given env"
    value: ${{ steps.get-settings.outputs.aws_region }}
  app_name: 
    description: "app or service name"
    value: ${{ steps.get-settings.outputs.app_name }}
  prefix:
    description: "env prefix"
    value: ${{ steps.get-settings.outputs.env_prefix }}

runs:
  using: 'composite'
  steps:
    - name: set Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: install yamcfg 
      shell: bash
      run: |
         pip install "${{ github.action_path }}/dist/yamlcfg-0.1.0.tar.gz"

    - name: get CI/CD environment settings
      id: get-settings
      shell: bash
      run: |
        yamlcfg --env ${{ inputs.env }} --role ${{ inputs.role }} --cfgfile ${{ inputs.config }}
     