name: Running make file 
description: "build, test, lint and codecoverage reports of the application"

inputs:
  python_version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}  
    - name: Create virtual env
      shell: bash
      run: make venv   
    - name: Install dependencies
      shell: bash
      run: make install    
    - name: Linting
      shell: bash
      run: make lint
    - name: Testing 
      shell: bash
      run: make test
    - name: Build Python package
      shell: bash
      run: make build    
    # - name: Coverage Reports 
    #   shell: bash
    #   run: make coverage 
         
