# push ML container(s) into three envs
name: build ML model container(s)
description: build ML model container

inputs:
  profile:
    description: ci/cd profile 
    required: true

runs:
    using: "composite"
    steps: 
    - name: build ML container(s) and push to Dev
      id: ml-container-build
      uses: Iterative-Scopes/cicd-framework/actions/build-ecr-ml-image@ISOPS-705-ml
      with:
        env: dev
        profile: ${{ inputs.profile }}
        build: 'YES'
        push: 'YES'
    
    - name: build ML container(s) and push to Prod
      id: ml-container-build
      uses: Iterative-Scopes/cicd-framework/actions/build-ecr-ml-image@ISOPS-705-ml
      with:
        env: production
        profile: ${{ inputs.profile }}
        build: 'NO'
        push: 'YES'

    - name: build ML container(s) and push to PHI
      id: ml-container-build
      uses: Iterative-Scopes/cicd-framework/actions/build-ecr-ml-image@ISOPS-705-ml
      with:
        env: phi
        profile: ${{ inputs.profile }}
        build: 'NO'
        push: 'YES'
