# app info
application:
  name: cicd-test-action  # name of application
  package:                # artifact package type and name
    registry: ecr         # ecr or s3 bucket name
    repository: cicd-framework # ecr repository or s3 folder
  runtime:
    name: go
    version: 1.4

# aws account info per env
aws:
  dev:
    account: 12313213
    region: global-east
    audience: sts.amazonaws.com
    sqs_url: sqs_url
  qa:
    account: 90232822
    region: global-west
    audience: sts.amazonaws.com
    sqs_url: sqs_url

role:
  build: 
    name: github-build
    duration: 1200
  deploy: 
    name: github-deploy
    duration: 600
  test: 
    name: github-test 
    duration: 1800



