name: build lambda package
description: build lambda package, return zip uri

inputs:
  env:
    description: environment to push package
    required: true
  registry: 
    description: "s3 bucket or ecr registry URI"
    required: true
  repository: 
    description: "app or service name"
    required: true
  make-directory:
    description: directory of makefile
    required: false
    default: $GITHUB_WORKSPACE

outputs:
  zip_uri:
    description: lambda package ref, ecr tag or zip file name
    value: ${{ steps.push-zip.outputs.zip_uri }}

# assume caller has connect to AWS account
runs:
    using: "composite"
    steps: 
    - name: Build lambda zip 
      id: build-zip
      shell: bash
      run: |
        echo "build zip..."
        make -C ${{ inputs.make-directory }} build
    - name: Push to lambda registry s3
      id: push-zip
      shell: bash
      run: |
        echo "push zip..."
        aws s3 cp ${{ inputs.repository }}.zip ${{ inputs.registry }}/${{ inputs.env }}/${{ inputs.repository }}.zip
        echo "::set-output name=zip_uri::${{ inputs.registry }}/${{ inputs.env }}"