name: build ecr image
description: build a container image and push to ecr

inputs:
  aws_account:
    description: aws account
    required: true
  aws_role:
    description: aws role
    required: true
  aws_region:
    description: aws region
    required: true
  ecr_repository:
    description: aws repository
    required: true
  make_cmd: 
    description: make command
    default: container
    required: true

runs:
    using: "composite"
    steps: 
      - name: Connect to AWS 
        uses: Iterative-Scopes/cicd-framework/actions/aws-login@main
        with:
          aws_region: ${{ inputs.aws_region }}  
          role_arn: arn:aws:iam::${{ inputs.aws_account }}:role/${{ inputs.aws_role }}
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env: 
          aws_region: ${{ inputs.aws_region }}
    
      - name: Build, tag, and push image to Amazon ECR
        env:
          REMOTE_REGISTRY: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}
          IMAGE_TAG: ${{ github.ref_name }}
        shell: bash
        run: |
          make ${{ inputs.make_cmd }} remotereg="$REMOTE_REGISTRY" tag="$IMAGE_TAG"
          make ${{ inputs.make_cmd }}test
          docker push $REMOTE_REGISTRY:$IMAGE_TAG
