name: Connect to AWS
description: connect to AWS account associated with a given environment 

inputs:
  env:
    description: environment running on workflow
    required: true
  role: 
    description: role assumed to used to connect to AWS
    required: true
  profile:
    description: yaml config file 
    required: true

runs:
  using: "composite"
  steps:      
    - name: Get given environment AWS settings
      id: aws_settings
      uses: Iterative-Scopes/cicd-framework/actions/cicdcfg@ISOPS-533-aws-settings
      with:
        env: ${{ inputs.env }}
        role: ${{ inputs.role }}
        config: ${{ inputs.profile }}

    - name: Configure AWS credentials
      id: aws-configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ steps.aws_settings.outputs.aws_account }}:role/${{ steps.aws_settings.outputs.aws_role }}
        role-duration-seconds: ${{ steps.aws_settings.outputs.aws_role_duration }}
        aws-region: ${{ steps.aws_settings.outputs.aws_region }}
        audience: ${{ steps.aws_settings.outputs.aws_audience }}