name: Create Release
description: Creates release from tag
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release'
    required: true
  body:
    description: 'Text describing the contents of the tag'
    required: false
  repo:
    description: 'Repository on which to release'
    required: false 

 
runs:
  using: "composite"
  steps:      
    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: ${{ inputs.release_name }}
