name: integrate testing
description: "run integrate testing in a given env"

inputs:
  env:
    description: environment to run tests
    required: true
  profile:
    description: cicd profile
    required: true
  make-directory:
    description: directory of makefile
    required: false
    default: $GITHUB_WORKSPACE

runs:
  using: "composite"
  steps:
    - name: Configure aws to run integration testing
      uses: Iterative-Scopes/cicd-framework/actions/connect2aws@main
      with:
        env: ${{ inputs.env }}
        role: test
        profile: ${{ inputs.profile }}

    # Run integration testing  
    - name: Integration testing
      shell: bash
      run: |
        echo "run integration testing"
        make -C ${{ inputs.make-directory }} integrationtest