name: deploy lambda
description: update lambda with container, S3 or zip 

inputs:
  env:
    description: environment hosting lambda 
    required: true
  profile:
    description: environment profile 
    required: true
  package_ref: 
    description: lambda package ref from lambda build job
    required: true
    default: "null"

runs:
    using: "composite"
    steps: 
      - name: Get given application settings
        id: app_settings
        uses: Iterative-Scopes/cicd-framework/actions/cicdcfg@main
        with:
          env: ${{ inputs.env }}
          role: deploy
          profile: ${{ inputs.profile }}

      - name: Validate package ref and setup lambda name
        shell: bash
        run: |
          echo LAMBDA_NAME=${{ inputs.env }}-${{ steps.app_settings.outputs.app_name }} >> $GITHUB_ENV
          if [ $LAMBDA_NAME == "null" || ${{ inputs.package_ref }} == "null" ]; 
          then
            echo "Missing package ref [${{ inputs.package_ref }}] or lambda name: [$LAMBDA_NAME]";
            exit 128;
          fi;

      - name: Configure AWS credentials
        id: aws-configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ steps.app_settings.outputs.aws_account }}:role/${{ steps.app_settings.outputs.aws_role }}
          role-duration-seconds: ${{ steps.app_settings.outputs.aws_role_duration }}
          aws-region: ${{ steps.app_settings.outputs.aws_region }}
          audience: ${{ steps.app_settings.outputs.aws_audience }}

      - name: Update container lambda - get image uri with given image tag
        if: ${{ steps.app_settings.outputs.app_registry == 'ecr' }}
        uses: Iterative-Scopes/cicd-framework/actions/get-ecr-image-uri@main
        id: get-image-uri
        with: 
          aws_region: ${{ steps.app_settings.outputs.aws_region }}
          repository: ${{ steps.app_settings.outputs.app_repository }}
          image_tag: ${{ inputs.package_ref }} 

      - name: Update container lambda - update lambda with image uri
        if: ${{ steps.app_settings.outputs.app_registry == 'ecr' && 
              steps.get-image-uri.outputs.uri }}
        shell: bash
        run: |
          echo ${{ steps.get-image-uri.outputs.uri }}
          aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --image-uri ${{ steps.get-image-uri.outputs.uri }}
          exit 0
  
      - name: Update lambda from S3 registry
        if: contains(${{ steps.app_settings.outputs.app_registry}}, "s3:::")
        shell: bash
        run: |
          echo "update lambda with [${{ inputs.package_ref }}]"
          aws lambda update-function-code --dry-run --function-name  ${{ steps.app_settings.outputs.app_repository}}-${{ inputs.env }}-lookup_patient_data --s3-bucket dev-is-phi-infrastructure --s3-key serverless/dev/${{ steps.app_settings.outputs.app_repository}}.zip 
          exit 0