name: Setup AWS OIDC IAM Role via sharableaction

inputs:
  aws_region:
    required: true
    type: string
  role_arn:
    required: true
    type: string

runs:
  using: "composite"
  steps:      
    - name: Configure AWS credentials
      id: aws-configure
      shell: bash
      run: |
        export AWS_ROLE_ARN=${{inputs.role_arn}}
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        export AWS_DEFAULT_REGION=${{inputs.aws_region}}
        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE     
