name: Automerge the PR when all requirements met.

on:
	workflow_call:
	    inputs:
      python_version:
        description: python version
        required: true
        type: string
      aws_account:
        description: aws account
        required: true
        type: string
      aws_role:
        description: aws role
        required: true
        type: string
      aws_region:
        description: aws region
        required: true
        type: string

jobs:
	build:
		runs-on: ubuntu-latest
		steps: 
			- name: Checkout
				uses: actions/checkout@v3

			- name: Retrieve Secrets
				id: secrets
				uses: t-botz/aws-secrets-manager-read-action@v2
				env: 
					AWS_REGION: ${{ inputs.aws_region }}
				with:
					secret-id: github_actions_gh_token
					keys-as-env-vars: true
					keys-as-outputs: true
					append-to-env-file: ./my.env
					AWS_REGION: ${{ inputs.aws_region }}
		 
			- name: Automatically Merge PR
				uses: Iterative-Scopes/cicd-framework/actions/pr-merge@ISOPS-532-pr-checks
				with:
					# GitHub WebHook Secret Token
					github-token: ${{ secrets.GITHUB_TOKEN }}
					# The number of reviewers to automatically merge. Default is 1.
					min-approvals: 1
					# The merge method ("merge", "squash", "rebase"). Default is "merge"
					merge-method: merge
					# Let the bot delete the merged branch. true or false.
					auto-delete: false
					dry-run: true 