name: Create a new release

on:
  push:
    tags:
      # Only semantic version tags should trigger
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Echo the workflow triggering github tag
        run: echo '::debug::New tag created'