name: Create a new rc tag

on:
  push:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      rc-tag:
        description: give a semantic version tag
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Validate input RC tag
        uses: Iterative-Scopes/cicd-framework/actions/validate-rc-tag@isops-503
        with:
          # tag: ${{ inputs.rc-tag }}
          tag: 1.0.1