# This file is the sharable workflow for runnning  integration test.
# The sharable workflow can be used across applications by referring this action in the github workflow. 

name: Integration test

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make integrationtest

# jobs:
#   Integration-test:
#     runs-on: ubuntu-latest
		# steps:
		#   - name: Checkout
		#     uses: actions/checkout@v3 
		#   - name: Testing 
		#     run: make integrationtest 