name: ML build and publish container artifact

on:
  workflow_call:
    inputs:
      python_version:
        description: python version
        required: true
        type: string
      secret_id:
        description: secret id
        required: true
        type: string
      aws_account:
        description: aws account
        required: true
        type: string
      aws_role:
        description: aws role
        required: true
        type: string
      aws_region:
        description: aws region
        required: true
        type: string
      ecr_repository:
        description: ecr repository
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to AWS 
        uses: Iterative-Scopes/cicd-framework/actions/aws-login@main
        with:
          aws_region: ${{ inputs.aws_region }}  
          role_arn: arn:aws:iam::${{ inputs.aws_account }}:role/${{ inputs.aws_role }}
    
      - name: Retrieve Secrets
        id: secrets
        shell: bash
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id ${{ inputs.secret_id }} --region ${{ inputs.aws_region }} --query SecretString --output text)
      
      # use ci/cd framework action python-build
      - name: cpu-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/ml-build@ISOPS-462
        env: 
          GH_ACCESSTOKEN_SECRET: ${{ steps.secrets.outputs.secret }}
        with:
          python_version: ${{ inputs.python_version }}
          build_type: cpu    
            
      # use ci/cd framework action build-ecr-image
      - name: Build, tag, and push image CPU to Amazon ECR
        uses: Iterative-Scopes/cicd-framework/actions/build-ecr-image@ISOPS-462
        with:
          aws_account: ${{ inputs.aws_account }}
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          ecr_repository: ${{ inputs.ecr_repository }}
          secret_id: ${{ inputs.secret_id }}

      - name: gpu-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/ml-build@ISOPS-462
        env: 
          GH_ACCESSTOKEN_SECRET: ${{ steps.secrets.outputs.secret }}
        with:
          python_version: ${{ inputs.python_version }}
          build_type: gpu

      - name: Build, tag, and push image GPU to Amazon ECR
        uses: Iterative-Scopes/cicd-framework/actions/build-ecr-image@ISOPS-462
        with:
          aws_account: ${{ inputs.aws_account }}
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          ecr_repository: ${{ inputs.ecr_repository }}
          secret_id: ${{ inputs.secret_id }}
      
