name: ML build and publish container artifact

on:
  workflow_call:
    inputs:
      python_version:
        description: python version
        required: true
        type: string
      aws_account:
        description: aws account
        required: true
        type: string
      aws_role:
        description: aws role
        required: true
        type: string
      aws_region:
        description: aws region
        required: true
        type: string
      repository:
        description: ecr repository
        required: true
        type: string 

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download ml-common artifact 
        uses: actions/download-artifact@master
        with:
          name: ml_common_artifact
          path: ml-common
    
      # use ci/cd framework action python-build
      - name: cpu-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/python-build@ISOPS-548
        with:
          python_version: ${{ inputs.python_version }} 
            
      # use ci/cd framework action build-ecr-image
      - name: Build, tag, and push image CPU to Amazon ECR
        uses: Iterative-Scopes/cicd-framework/actions/build-ecr-image@ISOPS-548
        with:
          aws_account: ${{ inputs.aws_account }}
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          repository: ${{ inputs.repository }}
          make_cmd: cpu

      - name: gpu-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/python-build@ISOPS-548
        with:
          python_version: ${{ inputs.python_version }}

      - name: Build, tag, and push image GPU to Amazon ECR
        uses: Iterative-Scopes/cicd-framework/actions/build-ecr-image@ISOPS-548
        with:
          aws_account: ${{ inputs.aws_account }}
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          repository: ${{ inputs.repository }}
          make_cmd: gpu