name: python build and publish container artifact

on:
  workflow_call:
    inputs:
      python_version:
        description: python version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      # use ci/cd framework action python-build
      - name: python-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/python-build@ISOPS-532
        with:
          python_version: ${{ inputs.python_version }}
