name: python build and publish container artifact

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Create virtual env
        run: make venv 
      - name: Lint
        run: make lint
      - name: Testing 
        run: make test
      - name: Build python package
        run: make build 
      - name: Build container 
        run: make container
      - name: Test container 
        run: make test-container
      - name: publish container
        run: echo "use sharable publish"


