name: python build and publish container artifact

on:
  workflow_call:
    inputs:
      python_version:
        description: python version
        required: true
        type: string
      aws_account:
        description: aws account
        required: true
        type: string
      aws_role:
        description: aws role
        required: true
        type: string
      aws_region:
        description: aws region
        required: true
        type: string
      ecr_repository:
        description: ecr repository
        type: string
        default: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      # use ci/cd framework action python-build
      - name: python-build-test  
        uses:  Iterative-Scopes/cicd-framework/actions/python-build@main
        with:
          python_version: ${{ inputs.python_version }}
      # use ci/cd framework action build-ecr-image
      - name: Build, tag, and push image to Amazon ECR
        #if: ${{ contains(inputs.ecr_repository) }}
        if: inputs.ecr_repository != 'default'
        uses: Iterative-Scopes/cicd-framework/actions/build-ecr-image@main
        with:
          aws_account: ${{ inputs.aws_account }}
          aws_role: ${{ inputs.aws_role }}
          aws_region: ${{ inputs.aws_region }}
          ecr_repository: ${{ inputs.ecr_repository }}
