name: sharable action unit testing
on: [push]

jobs:
  # unit test on ymalcfg
  test-yamlcfg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test 
        id: unittest
        uses: Iterative-Scopes/cicd-framework/actions/yamlcfg@ISOPS-533-aws-settings
        with:
          env: dev
          role: test
          config: "$GITHUB_WORKSPACE/.cicd-cfg.yml"


      - name: Check outputs
        run: |
          echo "aws account: ${{ steps.unittest.outputs.aws_account }}"
          test "${{ steps.unittest.outputs.aws_account }}" == "12313213"
          echo "aws role: ${{ steps.unittest.outputs.aws_role }}"
          test "${{ steps.unittest.outputs.aws_role }}" == "github-test"
          echo "aws region: ${{ steps.unittest.outputs.aws_region }}"
          test "${{ steps.unittest.outputs.aws_region }}" == "global-east"
          echo "app name: ${{ steps.unittest.outputs.app_name }}"
          test "${{ steps.unittest.outputs.app_name }}" == "cicd-test-action"
  
  # unit testing on build-source
  test-build-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Python
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings
        with:
          runtime: python
          version: 9.3

      - name: Test Node 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: node
          version: 12

      - name: Test un-supported runtime 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: java
          version: 12
          continue-on-error: true
