name: sharable action unit testing
on: [push]

jobs:
  # unit test on connec2aws
  test-aws-config:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Configure AWS credentials
      id: aws-configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.IS_AWS_ACCOUNT }}:role/${{ secrets.IS_AWS_ASSUME_ROLE }}
        role-duration-seconds: 60
        aws-region: us-east-1
        audience: ${{ secrets.IS_AWS_AUDIENCE }}

  # unit test on cicdcfg
  test-cicdcfg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test 
        id: unittest
        uses: Iterative-Scopes/cicd-framework/actions/cicdcfg@ISOPS-533-aws-settings
        with:
          env: dev
          role: test
          profile: "$GITHUB_WORKSPACE/.cicd-profile.yml"


      - name: Check outputs
        run: |
          test "${{ steps.unittest.outputs.aws_account }}" == "12313213"
          test "${{ steps.unittest.outputs.aws_region }}" == "global-east"
          test "${{ steps.unittest.outputs.aws_audience }}" == "sts.amazonaws.com"
          test "${{ steps.unittest.outputs.aws_role }}" == "github-test"
          test "${{ steps.unittest.outputs.aws_role_duration }}" == "1800"
          test "${{ steps.unittest.outputs.app_name }}" == "cicd-test-action"
  
  # unit testing on build-source
  test-build-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Python
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings
        with:
          runtime: python
          version: 3.9

      - name: Test Node 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: node
          version: 12

      - name: Test un-supported runtime 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: java
          version: 12
        continue-on-error: true
