name: build source unit testing
on: [push]

jobs:
 test-build-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Python
        id: rt-python
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings
        with:
          runtime: python
          version: 9.3

      - name: Test Node 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: node
          version: 12

      - name: Test un-supported runtime 
        uses: Iterative-Scopes/cicd-framework/actions/build-source@ISOPS-533-aws-settings 
        with:
          runtime: java
          version: 12

      

